services:
  postgres:
    image: postgres:15
    container_name: url_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/bryanr1910/url-shortener:latest
    container_name: url-api
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    env_file:
      - .env

volumes:
  postgres_data:
